# Generated by Django 4.0.4 on 2022-05-26 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendanceapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professor',
            name='user_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='filed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='m_ageunder80',
            name='missingperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.missingperson'),
        ),
        migrations.AddField(
            model_name='m_ageunder60',
            name='missingperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.missingperson'),
        ),
        migrations.AddField(
            model_name='m_ageunder40',
            name='missingperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.missingperson'),
        ),
        migrations.AddField(
            model_name='m_ageunder20',
            name='missingperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.missingperson'),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='filed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='course_proff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.professor'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject_attende',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.student'),
        ),
        migrations.AddField(
            model_name='ageunder80',
            name='foundperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.foundperson'),
        ),
        migrations.AddField(
            model_name='ageunder60',
            name='foundperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.foundperson'),
        ),
        migrations.AddField(
            model_name='ageunder40',
            name='foundperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.foundperson'),
        ),
        migrations.AddField(
            model_name='ageunder20',
            name='foundperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.foundperson'),
        ),
    ]
