# Generated by Django 4.0.4 on 2022-05-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0002_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_time', models.IntegerField(unique=True)),
                ('course_proff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.professor')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_attende', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.student')),
                ('course_proff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.professor')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.course')),
                ('subject_attende', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.student')),
            ],
        ),
    ]
