# Generated by Django 4.0.1 on 2022-05-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0003_course_team_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='testingmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='SOME stirng', upload_to='upload/')),
            ],
        ),
    ]
