# Generated by Django 4.0.1 on 2022-05-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0005_remove_professor_photo_professor_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='can_mark_attendance_now',
            field=models.BooleanField(default=False),
        ),
    ]
