# Generated by Django 4.0.1 on 2022-05-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0006_remove_attendance_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faceid1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='faceid2',
            field=models.CharField(default='', max_length=150),
        ),
    ]
