# Generated by Django 4.0.1 on 2022-05-15 20:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0007_student_faceid1_student_faceid2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
