# Generated by Django 4.0.1 on 2022-05-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0009_alter_student_photo_alter_testingmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo_to_be_matched',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
