# Generated by Django 4.0.1 on 2022-05-18 18:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0010_student_photo_to_be_matched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foundperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('father', models.CharField(max_length=150)),
                ('mother', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=150)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Missingperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('father', models.CharField(max_length=150)),
                ('mother', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=150)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='M_ageunder80',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.missingperson')),
            ],
        ),
        migrations.CreateModel(
            name='M_ageunder60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.missingperson')),
            ],
        ),
        migrations.CreateModel(
            name='M_ageunder40',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.missingperson')),
            ],
        ),
        migrations.CreateModel(
            name='M_ageunder20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missingperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.missingperson')),
            ],
        ),
        migrations.CreateModel(
            name='ageunder80',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.foundperson')),
            ],
        ),
        migrations.CreateModel(
            name='ageunder60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.foundperson')),
            ],
        ),
        migrations.CreateModel(
            name='ageunder40',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.foundperson')),
            ],
        ),
        migrations.CreateModel(
            name='ageunder20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.foundperson')),
            ],
        ),
    ]
