# Generated by Django 4.0.1 on 2022-05-19 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendanceapp', '0011_foundperson_missingperson_m_ageunder80_m_ageunder60_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_ageunder40',
            old_name='foundperson',
            new_name='missingperson',
        ),
        migrations.RenameField(
            model_name='m_ageunder60',
            old_name='foundperson',
            new_name='missingperson',
        ),
        migrations.RenameField(
            model_name='m_ageunder80',
            old_name='foundperson',
            new_name='missingperson',
        ),
        migrations.AddField(
            model_name='foundperson',
            name='filed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missingperson',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='filed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
