# Generated by Django 4.0.1 on 2022-05-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0012_rename_foundperson_m_ageunder40_missingperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundperson',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
