# Generated by Django 4.0.1 on 2022-05-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0013_foundperson_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
